---
title: "MRMC Practice"
author: "남승찬"
date: '2022년 1월 25일 (화)'
output:
  html_document:
    theme: default
    highlight: textmate
    toc: TRUE
    toc_depth: 3  
    toc_float: TRUE
    number_sections: FALSE

  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MRMCaov)
library(pROC)
head(VanDyke)
X <- VanDyke
```

## Reader Performance Metrics
### ROC Curve Metrics

```{r}
## Total area under the ROC curve
par(pty="s")
roc.info <- roc(X$truth, X$rating, plot=TRUE, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE)
roc.info$auc

## Partial area for specificity from 0.7 to 1.0
par(pty="s")
roc.info <- roc(X$truth, X$rating, plot=TRUE, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE,
partial.auc=c(0.7, 1), auc.polygon=TRUE, auc.polygon.col='#377eb822')
roc.info$auc

## Partial area for sensitivity from 0.7 to 1.0
par(pty="s")
roc.info <- roc(X$truth, X$rating, plot=TRUE, legacy.axes=TRUE, lwd=3, col='#377eb8', print.auc=TRUE,
partial.auc=c(1, 0.7), partial.auc.focus='sens', auc.polygon=TRUE, auc.polygon.col='#377eb822')
roc.info$auc

## Sensitivity for given specificity
coords(roc.info, 0.8, input='specificity')

## Specificity for given sensitivity
coords(roc.info, 0.8, input='sensitivity')
```

### Binary Metrics
```{r}
## Create binary classification
VanDyke$binary_rating <- VanDyke$rating >= 3
X <- VanDyke

## Sensitivity
table(real=X$truth, pred=X$binary_rating)
392/(58+392)

## Specificity
table(real=X$truth, pred=X$binary_rating)
585/(585+105)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
